# Simple Unified Model

How to value, hedge, and manage the risk of _any_
collection of instruments. $\AA$.  

There is a huge, unsolved problem in finance: How to value, hedge, and
manage the risk of portfolios of any collection of instruments.
Historically, banks and hedge funds have desks dedicated to
each product area such as
equities, fixed income, commodities, FX, etc. The modern world
requires a framework for understanding the correlation between these.
A common approach is to specify a copula. The Gaussian copula
led to the infamous 2008 debacle in structured credit markets.

Stephan Ross poinnted the way. This project extends his work by
adding an explicit knob for cash flows.

For full details see https://keithalewis.github.io/math/sum.html

If you know about finance but are not a mathematician see https://keithalewis.github.io/math/ross.html

The talk I gave for the general public at the Museum of Mathematics in December 2025 is
available at https://kalx.net/sum.html.

## Model

Let $T$ be a finite totally ordered set of _trading times_,
$I$ a finite set of _market instruments_,
$\Omega$ be the finite set of possible outcomes, and $(\AA_t)_{t\in T}$ be partitions of $\Omega$ representing information available at time $t\in T$.

We require for every $B\in \AA_t$ that $B = \cup\{A\subseteq B\mid A\in \AA_u\}$ when $u > t$.
This is weaker than the usual requirement that the algebras are refinements.

Recall $\tau\colon\Omega\to T$ is a stopping time if $\{\tau = t\}$ is a
union of atoms from $\AA_t$.

We assume everything is finite since that is the case when implementing
models on a computer.

### Price

The prices of instruments at
time $t\in T$ are a function
$X_t\colon \AA_t\to R^I$, where $R$ is
typically an IEEE 754 floating point number.
A better choice is to let $R$ be an integral
type to be multiplied by each instruments
minimum price increment to model possible
prices exactly.

### Cash Flow

The cash flows of instruments at
time $t\in T$ are a function
$C_t\colon \AA_t\to R^I$.
We can let $R$ be an integral type to
be multiplied by each instruments minimum cash flow increment to model possible cash flows
exactly.

### Trading

A trading strategy is a finite number of
increasing stopping times $\tau_0 < \cdots < \tau_n$ and functions $\Gamma_j\colon \AA_{\tau_j}\to R^I$.

Trades accumulate into a position 
$\Delta_t = \sum_{\tau_j < t} \Gamma_j = \sum_{s < t} \Gamma_s$ where
$\Gamma_s = \Gamma_j$ if $s = \tau_j$, and
is zero otherwise.
Note the strict inequality. It takes some time for trades to settle.

A trading strategy is _closed out_ if $\sum_j \Gamma_j = 0$.

### Accounting

Define the _value_ (or _mark-to-market_) at time $t$ of a trading strategy by
$V_t = (\Delta_t + \Gamma_t)\cdot X_t$. It is how much you get from liquidating
the existing position and the trades just done at current market prices.
Note $\Delta_t + \Gamma_t = \Delta_{t + \epsilon}$ for sufficiently small $\epsilon > 0$.

The _amounts_ generated by the trading strategy are
$A_t = \Delta_t\cdot C_t - \Gamma_t\cdot X_t$. You get cash flows proportional
to your existing position and pay for the trades just executed.

## Arbitrage

Arbitrage exists (in this model) if there is a trading strategy
$(\tau_j, \Gamma_j)$ with $A_{\tau_0} > 0$,
$A_t \ge 0$ for $t > \tau_0$, and $\sum_j \Gamma_j = 0$.
You make money on the first trade, never lose money after that,
and eventually close out. 

Note this definition of arbitrage does not involve probability.

Every arbitrage-free model has the form 
$$
X_t D_t = X_0 M_t - \sum_{s \le t} (C_s D_s)|_{\mathcal{A}_t},
$$
where $M_t$ is a vector-valued martingale measure
($M_t = M_u|_{\AA_t}$ for $t\le u$) and $D_t$ are positive finitely-additive measures 
$D_t\in ba(\AA_t)$. If a money market account is available then $D_t$ can
be chosen to be the reciprocal of its price. This is typically referred
to as the stochastic discount.

This implies

$$
X_t D_t = (X_u D_u + \sum_{t < s \le u} C_s D_s)|_{\AA_t}\quad\text{(1)}
$$

In the case of zero cash flows this says $(X_t D_t)$
is a martingale measure (Samuelson, Black-Scholes/Merton).
If $X_u D_u$ goes to zero as
$u$ goes to infinity, this says price is the discounted
value of future cash flows (Graham-Todd).

A consequence of (1) and our accounting definitions is

$$
V_t D_t = (V_u D_u + \sum_{t < s \le u} A_u D_u)|_{\AA_t}\quad\text{(2)}
$$

Note how price in (1) corresponds to value in (2)
and cash flows in (1) corresponds amount in (2).

> **Trading strategies create synthetic market instruments.**

## Hedging

If a cash-settled derivative pays $\hat{A_j}$ at
increasing stopping times $\hat{\tau}_j$ then its value
at time $t$ is determined by

$$
V_t D_t = (\sum_{\hat{\tau}_j > t} \hat{A_j} D_{\hat{\tau}_j})|_{\AA_t}.\quad\text{(3)}
$$

_if_ we can find a trading strategy with $A_t - \hat{A}_j 1(t = \hat{\tau}_j) = 0$
for all $t\in T$. [^1]

[^1]: In general this is not possible. An area for future research
is to find trading strategies making the difference
white noise with minimum variance a la
Markowitz.

Since $V_t = (\Delta_t + \Gamma_t)\cdot X_t$ we have the
Fréchet derivative $D_{X_t} V_t = \Delta_t + \Gamma_t$.
Since the position at time 0 is $\Delta_0 = 0$ this gives us
our first trade $\Gamma_0 = D_{X_0} V_0$.
At times greater than 0 we have $\Gamma_t = D_{X_t} V_t - \Delta_t$.
Since $\Delta_t$ is the accumulation of prior trades, 
this determined $\Gamma_t$. 

What this _does not_ determine is
when to trade. If we trade at positive integral multiples of some
fixed $\Delta t$ and let $\Delta t \to 0$ then we get the usual
Black-Scholes/Merton continuous time delta hedging strategy.

## Implementation

The value at time $t$ of an option paying
$A_\tau$ at stopping time $\tau$ is determined
by 
$$
V_t D_t = (1(\tau > t) A_\tau D_\tau)|_{\AA_t}
$$

So for $E\in \AA_t$ we have
$$
(V_t D_t)(E) = \sum_{u > t} \sum_{F\subseteq E\cap\{\tau = u\}} A_u(F) D_u(F)
$$

Given $E\in \AA_t$ and $u > t$ we need to produce the collections
$$
\{F\in \AA_u\mid F\subset E\cap\{\tau = u\}\}
$$
to calculate the sum/product.


